import 'dart:developer' as developer;
import 'package:flutter/foundation.dart';
import 'package:google_sign_in/google_sign_in.dart';

class GoogleSignInProvider extends ChangeNotifier{
//eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2M2RiZTczYWFkODhjODU0ZGUwZDhkNmMwMTRjMzZkYzI1YzQyOTIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiNjQ1NDE0NTYwMDU4LWc0NG9lbmhtZ2U0Nm9tbTkycTNxajNrNXFxaXN2MXIxLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiNjQ1NDE0NTYwMDU4LWc0NG9lbmhtZ2U0Nm9tbTkycTNxajNrNXFxaXN2MXIxLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE1NDE5MTE4MDExNTUzODQ4NzEwIiwiZW1haWwiOiJiYWJha3Rlc3RnYWhyZW1hbnphZGVoQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiYjhzb0Y4OVdfeVFaQ1FwZ1VtbFZoUSIsIm5hbWUiOiJBcmlhbmEgUnoiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUFUWEFKeW1Zdm1fODF6LTBYRDVIV2xuc3ZDVUVMQXRfYWJiOG52N3Q5N289czk2LWMiLCJnaXZlbl9uYW1lIjoiQXJpYW5hIiwiZmFtaWx5X25hbWUiOiJSeiIsImxvY2FsZSI6ImVuIiwiaWF0IjoxNjQ2NzUzMjY0LCJleHAiOjE2NDY3NTY4NjQsImp0aSI6ImNjODU1ZjZhYmMyYTFlZjFlYjU3ODc5MGY2Mzk3NDJkNTg2NWEzY2UifQ.FE60SAz3LhhVQp1m6oYjbToIRoZ9yTWE2FvQllcVGANCNdhEliJp4nsbbqxAIWoagoE6ohvE700zv9xykEoN5RlQovC4jI23n4RFSnLj3R5fnpwFvWuQDpIqy3L8Xlrg1UBcy5xeJrHePbqes6iNFhRGaV5eyJ6BJiOnYZ27QuauR3AGeCYrw73ocLj8oflanB6_PKwi7-RajbqKfFnTuvpc5nSbCGBai_Iy2FqxVlq6aunLFlcUrHXcvSkJmJeF87UQLyt1wSHXi3wcPAjXmnpLmWCrgHRYkTzxsgLibr1noOxMiQj9oLRYVbUc_NSQmOsRwbPt_E2ZAq_Tq-PzKA
//eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ2M2RiZTczYWFkODhjODU0ZGUwZDhkNmMwMTRjMzZkYzI1YzQyOTIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiNjQ1NDE0NTYwMDU4LWc0NG9lbmhtZ2U0Nm9tbTkycTNxajNrNXFxaXN2MXIxLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiNjQ1NDE0NTYwMDU4LWc0NG9lbmhtZ2U0Nm9tbTkycTNxajNrNXFxaXN2MXIxLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTE1NDE5MTE4MDExNTUzODQ4NzEwIiwiZW1haWwiOiJiYWJha3Rlc3RnYWhyZW1hbnphZGVoQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiTjdrTUVDSkNBcHBpVmI4TUhOZ0tfZyIsIm5hbWUiOiJBcmlhbmEgUnoiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUFUWEFKeW1Zdm1fODF6LTBYRDVIV2xuc3ZDVUVMQXRfYWJiOG52N3Q5N289czk2LWMiLCJnaXZlbl9uYW1lIjoiQXJpYW5hIiwiZmFtaWx5X25hbWUiOiJSeiIsImxvY2FsZSI6ImVuIiwiaWF0IjoxNjQ2NzUzMTA3LCJleHAiOjE2NDY3NTY3MDcsImp0aSI6IjM0OGU0NWQzNGQ2YTZhNzIyNTNhODUwMzVlMzk3OTA1MTVlNjM3OWYifQ.aoAG-kDKGXpg8XhgY_Wrwx-yGHwZW3UPiYnXQAEhc4-bjDW3wj7BHRofjU5ZkJ0FDstWyEqt93TH5zHYpHRuSQL-lDMC5hg7NHFGwiQEzb08tii2CmDeVannWEVBE4iPvU61UKyor6rlx8GcZqbilRvCYsukKrMDLY26wlwNpReWgYf-M51OJDiUWmYtO7Av1E9oI4MYMgIYBRq7cRlbUWfV3Za13KygY5x52tE-N-sJ9bKXKWww0f6t61jBCLtik8APXT6fWEtbYsV0zel58QL-QaZ_uULbG_sK1I_669YO6nkKC3iwormij24b-CKsZh0LrUxk5ap7vs0qKh0axg
  var googleSignIn = GoogleSignIn();

  GoogleSignInAccount get user => _user!;

  GoogleSignInAccount? _user;

  Future googleLogin() async {
     final googleUser = await googleSignIn.signIn();
     if(googleUser == null) return;

     _user = googleUser;

     final googleAuth = await googleUser.authentication;

     print("accessToken => ${googleAuth.accessToken}" );
     print("idToken => ${googleAuth.idToken}");

     // final credential = GoogleAuthProvider.credential(
     //   accessToken: googleAuth.accessToken,
     //   idToken: googleAuth.idToken
     // );
     //
     // await FirebaseAuth.instance.signInWithCredential(credential);
  }
}